### PR TITLE
Add distconfig to use newer virtualenv versions

### PR DESCRIPTION
**Pull request by marcoesters**
`virtualenv` requires `platformdirs` to run at version `20.5.0` and above: https://github.com/pypa/virtualenv/compare/20.4.6...20.5.0#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R45

This will cause `poetry` to fail for `python 3.10`. ~To avoid adding another dependency, pin the version to below `20.5.0`~ Add `distconfig` to the requirements to allow for newer `virtualenv` versions.

# Package info

Home: https://python-poetry.org/
Doc: https://python-poetry.org/docs
Dev: https://github.com/python-poetry/poetry/

### CODE REVIEW

**Comment by AndrewVallette** [comment]
LGTM

**Review by varlackc — COMMENTED** [review]
There seem to be a redirect in the `home url` to the following `url`
https://python-poetry.org/

**Review by AndrewVallette — APPROVED** [review]

**Comment by AndrewVallette** [comment]
> There seem to be a redirect in the `home url` to the following `url` https://python-poetry.org/

Thats true, it may as well be updated. Otherwise looks good to me.

**Comment by marcoesters** [comment]
> There seem to be a redirect in the `home url` to the following `url` https://python-poetry.org/

Good catch, thank you!

**Comment by skupr-anaconda** [comment]
> `virtualenv` requires `platformdirs` to run at version `20.5.0` and above: [pypa/virtualenv@20.4.6...20.5.0#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R45](https://github.com/pypa/virtualenv/compare/20.4.6...20.5.0#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R45)
> 
> This will cause `poetry` to fail for `python 3.10`. To avoid adding another dependency, pin the version to below `20.5.0`

I think this causes the issue https://github.com/AnacondaRecipes/platformdirs-feedstock/blob/75b94304d69dd4dd962e679971944daa8504bd7a/recipe/meta.yaml#L36
What if we will update `platformdirs` to the latest version 2.5.2?

**Comment by skupr-anaconda** [comment]
I'm rebuilding `platformdirs` to 2.5.2 to enable python 3.10 support https://github.com/AnacondaRecipes/platformdirs-feedstock/pull/2

**Comment by marcoesters** [comment]
> > `virtualenv` requires `platformdirs` to run at version `20.5.0` and above: [pypa/virtualenv@20.4.6...20.5.0#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R45](https://github.com/pypa/virtualenv/compare/20.4.6...20.5.0#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R45)
> > This will cause `poetry` to fail for `python 3.10`. To avoid adding another dependency, pin the version to below `20.5.0`
> 
> I think this causes the issue https://github.com/AnacondaRecipes/platformdirs-feedstock/blob/75b94304d69dd4dd962e679971944daa8504bd7a/recipe/meta.yaml#L36 What if we will update `platformdirs` to the latest version 2.5.2?

Possibly. Let's see where it goes once the new platformdirs is in default. This will have to stay open for a while anyway until the s360x platform is available again.

**Comment by skupr-anaconda** [comment]
`platformdirs 2.5.2` is available on defaults

**Comment by marcoesters** [comment]
> `platformdirs 2.5.2` is available on defaults except for `s390x` platforms

This builds, but now the question is: do we want pull in this extra dependency or just pin the virtualenv version?

**Comment by skupr-anaconda** [comment]
I'm not sure 100% but rebuilding with `platformdirs 2.5.2` and without that constraint for `virtualenv` would be a good solution

**Comment by marcoesters** [comment]
> I'm not sure 100% but rebuilding with `platformdirs 2.5.2` and without that constraint for `virtualenv` would be a good solution

Fair enough - I updated the PR to reflect that.

**Review by skupr-anaconda — APPROVED** [review]

**Pull request merged**
